### Spring properties
# Service registers under this name
spring:
  application:
    name: gis-pon-service

# Registry Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:9001/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 9002

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false